sudo: required
dist: trusty
before_install:
- sudo apt-get update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra texlive-humanities texlive-science latex-xcolor
  dvipng texlive-latex-recommended python-pygments
script:
- make travis
- sh upload_travis.sh
notifications:
  email: false
env:
  global:
    secure: "L0soXd0kpbYVc5U9GQww8ZNKxolsodQ55DAkAlQ0m3HVtwpMMRnKSnm6+NK3kBr9j8ceFiqReiKhpt0FuqMOTzq+enN7CSO8vFVPJhNuP1T8ajrjWOzzpItzCSLUPaH/o/46CojnYe4ct64cHGlfVPsb6BCumZRNdQpTlTxzS+m8zSdWoWz0mfnP62kd3VlkdhdXCJYQtONVIoPCAg6iZUAAo62AE8iSmFzGsn3zlTJVURSkL3JiMVR9rOWySqkxCJNmuy7FF7IZ4sfmbuge7M8EN4swrNct3RSOVkuwqL+FRT4WiJBMo7eWg/ezSAFe7vRlCleRkNFeHGx6oEsbMHajR0IQjGapjbjKYcFODv7urIwQYZPIArC7sQ9kfD/thyW2Mo0yqHEG9xdjRckEm98W31d1UmxiPx6mjivxG9WXaUO17Vl+kYveBqcx4ssRF+CrstCVuVVHh8e9sc6DsNlhDtychCbDEmsGOPE4UUifdASX9HwYgZ7JbIWY8Nj8VFLdWNb6ej1V+ug/7GSDNdfiU0VQZaLVl0oME5bgQv3PqB3FJBnFjhDzcviQWzbfI7C/w9A7Rr2pqRhy9HkJWdQ2hCItg2JRM16nNsv5BPzqw1K2BRZkaghbxZ7DBhK0qTrleg1/ThXLrthJ+QbpxKPehqDaUDUunp/KXdT9WFU="


